-- MySQL Script generated by MySQL Workbench
-- Tue Sep  5 23:13:17 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema apple
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `apple` ;

-- -----------------------------------------------------
-- Schema apple
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apple` DEFAULT CHARACTER SET utf8 ;
USE `apple` ;

-- -----------------------------------------------------
-- Table `apple`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apple`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `apple`.`Cliente` (
  `idCliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(200) NOT NULL,
  `cpfCliente` BIGINT UNSIGNED NOT NULL,
  `telCliente` VARCHAR(20) NULL,
  `celCliente` VARCHAR(20) NULL,
  `fotoFunc` VARCHAR(100) NULL,
  `ruaCliente` VARCHAR(100) NULL,
  `compCliente` VARCHAR(20) NULL,
  `numeroCliente` VARCHAR(10) NULL,
  `bairroCliente` VARCHAR(45) NULL,
  `cidadeCliente` VARCHAR(45) NULL,
  `cepCliente` BIGINT NULL,
  `dataNascCliente` DATE NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `cpfCliente_UNIQUE` (`cpfCliente` ASC),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apple`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apple`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `apple`.`Funcionario` (
  `idFuncionario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeFunc` VARCHAR(200) NOT NULL,
  `fotoFunc` VARCHAR(100) NULL,
  `salarioFunc` FLOAT UNSIGNED NOT NULL,
  `comissaoFunc` FLOAT UNSIGNED NOT NULL,
  `cpfFunc` BIGINT UNSIGNED NOT NULL,
  `ruaFunc` VARCHAR(100) NULL,
  `compFunc` VARCHAR(20) NULL,
  `numeroFunc` VARCHAR(10) NULL,
  `bairroFunc` VARCHAR(45) NULL,
  `cidadeFunc` VARCHAR(45) NOT NULL,
  `dataNascFunc` DATE NOT NULL,
  `telefoneFunc` VARCHAR(20) NULL,
  `celularFunc` VARCHAR(20) NULL,
  `dataAdmissaoFunc` DATE NOT NULL,
  `cepFunc` BIGINT UNSIGNED NOT NULL,
  `senhaFunc` VARCHAR(20) NOT NULL,
  `administrador` TINYINT(1) NULL,
  PRIMARY KEY (`idFuncionario`),
  UNIQUE INDEX `idFuncionario_UNIQUE` (`idFuncionario` ASC),
  UNIQUE INDEX `cpfFunc_UNIQUE` (`cpfFunc` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apple`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apple`.`Produto` ;

CREATE TABLE IF NOT EXISTS `apple`.`Produto` (
  `idProduto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(100) NOT NULL,
  `precoCompraProduto` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `precoVendaProduto` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `qtdEstoqueProduto` INT UNSIGNED NOT NULL DEFAULT 0,
  `fotoProduto` VARCHAR(100) NULL,
  `descricaoProduto` VARCHAR(200) NULL,
  `ultimaDataCompraProduto` DATE NULL,
  `dataCadastroProduto` DATE NULL,
  PRIMARY KEY (`idProduto`),
  UNIQUE INDEX `idProduto_UNIQUE` (`idProduto` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apple`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apple`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `apple`.`Pedido` (
  `idPedido` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Cliente_idCliente` INT UNSIGNED NOT NULL,
  `Funcionario_idFuncionario` INT UNSIGNED NOT NULL,
  `dataPed` DATE NULL,
  PRIMARY KEY (`idPedido`),
  UNIQUE INDEX `idPedido_UNIQUE` (`idPedido` ASC),
  INDEX `fk_Pedido_Cliente_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Pedido_Funcionario1_idx` (`Funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_Pedido_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `apple`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `apple`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apple`.`Gerente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apple`.`Gerente` ;

CREATE TABLE IF NOT EXISTS `apple`.`Gerente` (
  `idGerente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeGerente` VARCHAR(200) NOT NULL,
  `fotoGerente` VARCHAR(100) NULL,
  `salarioGerente` FLOAT UNSIGNED NOT NULL,
  `comissaoGerente` FLOAT UNSIGNED NOT NULL,
  `cpfGerente` BIGINT UNSIGNED NOT NULL,
  `ruaGerente` VARCHAR(100) NULL,
  `compGerente` VARCHAR(20) NULL,
  `numeroGerente` VARCHAR(10) NULL,
  `bairroGerente` VARCHAR(45) NULL,
  `cidadeGerente` VARCHAR(45) NOT NULL,
  `dataNascGerente` DATE NOT NULL,
  `telefoneGerente` VARCHAR(20) NULL,
  `celularGerente` VARCHAR(20) NULL,
  `dataAdmissaoGerente` DATE NOT NULL,
  `cepGerente` BIGINT UNSIGNED NOT NULL,
  `senhaGerente` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idGerente`),
  UNIQUE INDEX `idFuncionario_UNIQUE` (`idGerente` ASC),
  UNIQUE INDEX `cpfFunc_UNIQUE` (`cpfGerente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apple`.`Conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apple`.`Conta` ;

CREATE TABLE IF NOT EXISTS `apple`.`Conta` (
  `idConta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `aReceber` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `totalCompras` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `pago` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `Cliente_idCliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idConta`),
  UNIQUE INDEX `idConta_UNIQUE` (`idConta` ASC),
  INDEX `fk_Conta_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Conta_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `apple`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apple`.`Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apple`.`Compra` ;

CREATE TABLE IF NOT EXISTS `apple`.`Compra` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `nomeFornec` VARCHAR(45) NOT NULL,
  `cnpjFornec` VARCHAR(45) NOT NULL,
  `dataCompra` DATE NOT NULL,
  `outros` FLOAT UNSIGNED NULL,
  `valorTotal` FLOAT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCompra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apple`.`Pedido_has_Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apple`.`Pedido_has_Produto` ;

CREATE TABLE IF NOT EXISTS `apple`.`Pedido_has_Produto` (
  `Pedido_idPedido` INT UNSIGNED NOT NULL,
  `Produto_idProduto` INT UNSIGNED NOT NULL,
  `qtdVenda` INT UNSIGNED NOT NULL DEFAULT 0,
  `qtdControle` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`Pedido_idPedido`, `Produto_idProduto`),
  INDEX `fk_Pedido_has_Produto_Produto1_idx` (`Produto_idProduto` ASC),
  INDEX `fk_Pedido_has_Produto_Pedido1_idx` (`Pedido_idPedido` ASC),
  CONSTRAINT `fk_Pedido_has_Produto_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `apple`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `apple`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apple`.`Compra_has_Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apple`.`Compra_has_Produto` ;

CREATE TABLE IF NOT EXISTS `apple`.`Compra_has_Produto` (
  `Compra_idCompra` INT NOT NULL,
  `Produto_idProduto` INT UNSIGNED NOT NULL,
  `qtdControle` INT UNSIGNED NOT NULL DEFAULT 0,
  `qtdCompra` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`Compra_idCompra`, `Produto_idProduto`),
  INDEX `fk_Compra_has_Produto_Produto1_idx` (`Produto_idProduto` ASC),
  INDEX `fk_Compra_has_Produto_Compra1_idx` (`Compra_idCompra` ASC),
  CONSTRAINT `fk_Compra_has_Produto_Compra1`
    FOREIGN KEY (`Compra_idCompra`)
    REFERENCES `apple`.`Compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `apple`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
